import 'dart:async';
import 'dart:convert'; // Added for JSON utility handling if needed by components
import 'package:flutter/material.dart';
import 'package:kwagala_farm/Services/api_service.dart'; // 👈 Necessary connection service import

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  // Controller to handle the running notification ticker animation smoothly
  final ScrollController _tickerScrollController = ScrollController();
  Timer? _tickerTimer;

  // 👈 State indicators added to manage live network connection environments cleanly
  bool _isLoadingDashboard = true;
  String? _networkError;

  // Structured live feed alerts with their respective converted operational task text
  List<Map<String, String>> _tickerAlerts = [
    {
      "display": "⚠️ Alert: Severe rainfall tracking towards Kampala region this evening, secure shelters.",
      "task": "Secure shelters for evening severe rainfall alert"
    },
    {
      "display": "💉 Veterinary Schedule: 4 Kalahari breeders due for booster inoculations tomorrow.",
      "task": "Administer booster inoculations to Kalahari breeders"
    },
    {
      "display": "📈 Farm Analytics: Overall flock health optimization rating is holding steady at 96% variance capacity.",
      "task": "Review flock health optimization variance logs"
    },
  ];

  // Updated Checklist Array containing your newly converted task from chat
  List<Map<String, dynamic>> _dailyTasks = [
    {"id": null, "task": "Clean Paddock B water troughs", "done": true},
    {"id": null, "task": "Administer Dewormer to Boer group", "done": false},
    {"id": null, "task": "Confirm evening feed mix ratios", "done": false},
    {"id": null, "task": "Review flock health optimization variance logs", "done": false}, // Added from chat conversion
  ];

  @override
  void initState() {
    super.initState();
    // 👈 Load live records straight from Django database on system launch
    _syncDashboardWithBackend();
    // Setup automated micro-scrolling for our ticker bar after the frame renders
    WidgetsBinding.instance.addPostFrameCallback((_) => _startTickerAnimation());
  }

  // 👈 NEW METHOD: Synchronizes alerts and checklist datasets concurrently via Django ViewSets
  Future<void> _syncDashboardWithBackend() async {
    setState(() {
      _isLoadingDashboard = true;
      _networkError = null;
    });

    try {
      // Pull tasks and alerts concurrently from ApiService
      final liveAlertsList = await ApiService.fetchLiveAlerts();
      final liveTasksList = await ApiService.fetchTasks();

      setState(() {
        // Map Django Live Alerts into your local string payload formats if endpoints possess data
        if (liveAlertsList.isNotEmpty) {
          _tickerAlerts = liveAlertsList.map((alert) {
            String prefix = alert.severity.toLowerCase() == 'critical' ? "⚠️ CRITICAL: " : "ℹ️ Info: ";
            return {
              "display": "$prefix${alert.message}",
              "task": alert.message,
            };
          }).toList();
        }

        // Map Django tasks backend database cleanly directly over your fallback items
        if (liveTasksList.isNotEmpty) {
          _dailyTasks = liveTasksList.map((task) {
            return {
              "id": task.id, // Retain ID parameters for secure database toggle patches
              "task": task.title,
              "done": task.isDone,
            };
          }).toList();
        }
        
        _isLoadingDashboard = false;
      });
    } catch (e) {
      setState(() {
        _networkError = e.toString();
        _isLoadingDashboard = false;
      });
    }
  }

  // 👈 NEW METHOD: Controls interacting updates with the server registry whenever items are tapped
  void _toggleTaskDatabaseState(int index, Map<String, dynamic> task) async {
    // If the task wasn't generated by Django (id is null), handle toggle strictly on frontend
    if (task["id"] == null) {
      setState(() {
        _dailyTasks[index]["done"] = !task["done"];
      });
      return;
    }

    // Toggle local state immediately for snappy user tracking performance response
    setState(() {
      _dailyTasks[index]["done"] = !task["done"];
    });

    bool updateSuccess = await ApiService.toggleTaskStatus(task["id"], !task["done"]);
    
    // Roll back local changes if backend communication encounters roadblock errors
    if (!updateSuccess) {
      setState(() {
        _dailyTasks[index]["done"] = task["done"];
      });
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text("❌ Failed to synchronize checkbox update with live database."),
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  void _startTickerAnimation() {
    _tickerTimer = Timer.periodic(const Duration(milliseconds: 50), (timer) {
      if (_tickerScrollController.hasClients) {
        double maxExtent = _tickerScrollController.position.maxScrollExtent;
        double currentPosition = _tickerScrollController.position.pixels;
        
        // Loop back to start smoothly once it passes the text boundary
        if (currentPosition >= maxExtent) {
          _tickerScrollController.jumpTo(0.0);
        } else {
          _tickerScrollController.jumpTo(currentPosition + 1.0);
        }
      }
    });
  }

  // Business logic method to transform an in-app ticker message into an interactive checklist item
  void _convertAlertToTask(String taskTitle, String contextualAlert) {
    bool itemExists = _dailyTasks.any((element) => element["task"] == taskTitle);

    if (itemExists) {
      ScaffoldMessenger.of(context).clearSnackBars();
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text("ℹ️ '$taskTitle' is already listed in your operational checklist."),
          backgroundColor: Colors.amber.shade800,
          behavior: SnackBarBehavior.floating,
        ),
      );
      return;
    }

    setState(() {
      _dailyTasks.add({
        "id": null, // Local custom item allocation identifier marker
        "task": taskTitle,
        "done": false,
      });
    });

    ScaffoldMessenger.of(context).clearSnackBars();
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            const Icon(Icons.playlist_add_check_rounded, color: Colors.white),
            const SizedBox(width: 10),
            Expanded(
              child: Text(
                "Converted Alert into Task successfully!",
                overflow: TextOverflow.ellipsis,
                style: const TextStyle(fontWeight: FontWeight.w600),
              ),
            ),
          ],
        ),
        backgroundColor: Colors.green.shade800,
        behavior: SnackBarBehavior.floating,
        duration: const Duration(seconds: 3),
      ),
    );
  }

  // New helper method to display active notifications from the bell action icon
  void _showNotificationsPanel(BuildContext context) {
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) {
        return Container(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 20),
          height: 380,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  const Text(
                    "ACTIVE LIVE ALERTS",
                    style: TextStyle(
                      fontSize: 12, 
                      fontWeight: FontWeight.bold, 
                      letterSpacing: 1,
                      color: Color(0xFF64748B),
                    ),
                  ),
                  IconButton(
                    onPressed: () => Navigator.pop(context),
                    icon: const Icon(Icons.close_rounded, size: 20),
                  ),
                ],
              ),
              const SizedBox(height: 12),
              Expanded(
                child: ListView.separated(
                  itemCount: _tickerAlerts.length,
                  separatorBuilder: (context, index) => const Divider(height: 1, color: Color(0xFFE2E8F0)),
                  itemBuilder: (context, index) {
                    final alert = _tickerAlerts[index];
                    return Padding(
                      padding: const EdgeInsets.symmetric(vertical: 12.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            alert["display"]!,
                            style: const TextStyle(
                              fontSize: 13,
                              color: Color(0xFF0F172A),
                              fontWeight: FontWeight.w500,
                            ),
                          ),
                          const SizedBox(height: 8),
                          Align(
                            alignment: Alignment.centerRight,
                            child: ElevatedButton.icon(
                              onPressed: () {
                                Navigator.pop(context);
                                _convertAlertToTask(alert["task"]!, alert["display"]!);
                              },
                              icon: const Icon(Icons.bolt, size: 14, color: Colors.white),
                              label: const Text("Convert to Task", style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                              style: ElevatedButton.styleFrom(
                                backgroundColor: Colors.orange.shade700,
                                foregroundColor: Colors.white,
                                elevation: 0,
                                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                              ),
                            ),
                          )
                        ],
                      ),
                    );
                  },
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  @override
  void dispose() {
    _tickerTimer?.cancel();
    _tickerScrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final Color primaryGreen = Colors.green.shade700;
    final Color focusOrange = Colors.orange.shade700;

    return Scaffold(
      backgroundColor: const Color(0xFFF8F9FA),
      appBar: AppBar(
        automaticallyImplyLeading: false,
        elevation: 0,
        backgroundColor: Colors.white,
        titleSpacing: 24,
        shape: const Border(
          bottom: BorderSide(color: Color(0xFFE2E8F0), width: 1),
        ),
        title: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: Colors.green.shade50,
                borderRadius: BorderRadius.circular(10),
              ),
              child: Icon(Icons.agriculture_rounded, color: primaryGreen, size: 22),
            ),
            const SizedBox(width: 12),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Text(
                  "Kwagala Goat Farm",
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 16,
                    color: Color(0xFF0F172A),
                  ),
                ),
                Text(
                  "Kampala, Central Region",
                  style: TextStyle(fontSize: 12, color: Colors.grey.shade500, fontWeight: FontWeight.w500),
                ),
              ],
            ),
          ],
        ),
        actions: [
          // 👈 Added pulling swipe refresh option to refresh layout components on demand
          IconButton(
            icon: const Icon(Icons.refresh_rounded, color: Color(0xFF64748B)),
            onPressed: _syncDashboardWithBackend,
          ),
          IconButton(
            icon: const Icon(Icons.notifications_active_rounded, color: Color(0xFF64748B)),
            onPressed: () => _showNotificationsPanel(context),
          ),
          const SizedBox(width: 16),
        ],
      ),
      body: SafeArea(
        child: RefreshIndicator(
          onRefresh: _syncDashboardWithBackend,
          color: primaryGreen,
          child: SingleChildScrollView(
            physics: const AlwaysScrollableScrollPhysics(parent: BouncingScrollPhysics()),
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 24),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                
                // 👈 Optional warning bar communicating network roadblock boundaries gracefully
                if (_networkError != null)
                  Container(
                    width: double.infinity,
                    margin: const EdgeInsets.only(bottom: 16),
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                    decoration: BoxDecoration(color: Colors.amber.shade50, borderRadius: BorderRadius.circular(8)),
                    child: Text(
                      "Offline mode active. Showing saved tasks layout templates.",
                      style: TextStyle(color: Colors.amber.shade900, fontSize: 12, fontWeight: FontWeight.bold),
                    ),
                  ),

                // ================= ORIGINAL FULL PICTURE CARD BANNER =================
                Container(
                  width: double.infinity,
                  height: 160,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(16),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.08),
                        blurRadius: 12,
                        offset: const Offset(0, 4),
                      ),
                    ],
                    image: const DecorationImage(
                      image: AssetImage('assets/main1.jpg'),
                      fit: BoxFit.cover,
                    ),
                  ),
                  child: Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(16),
                      gradient: LinearGradient(
                        begin: Alignment.bottomCenter,
                        end: Alignment.topCenter,
                        colors: [
                          Colors.black.withOpacity(0.85),
                          Colors.black.withOpacity(0.20),
                        ],
                      ),
                    ),
                    padding: const EdgeInsets.all(20),
                    child: const Column(
                      mainAxisAlignment: MainAxisAlignment.end,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          "Kwagala Herd Hub",
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 22,
                            fontWeight: FontWeight.bold,
                            letterSpacing: 0.5
                          ),
                        ),
                        SizedBox(height: 4),
                        Text(
                          "Leading premium breed optimization registers in Uganda.",
                          style: TextStyle(
                            color: Color(0xFFE2E8F0),
                            fontSize: 13,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 24),

                // ================= PROFESSIONAL LIVE TICKER BANNER (INTERACTIVE) =================
                Container(
                  height: 38,
                  width: double.infinity,
                  decoration: BoxDecoration(
                    color: const Color(0xFF0F172A), 
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 12),
                        height: double.infinity,
                        decoration: BoxDecoration(
                          color: focusOrange,
                          borderRadius: const BorderRadius.only(
                            topLeft: Radius.circular(8),
                            bottomLeft: Radius.circular(8),
                          ),
                        ),
                        alignment: Alignment.center,
                        child: const Row(
                          children: [
                            Icon(Icons.sensors, color: Colors.white, size: 14),
                            SizedBox(width: 4),
                            Text(
                              "LIVE FEED",
                              style: TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.bold, letterSpacing: 0.5),
                            ),
                          ],
                        ),
                      ),
                      Expanded(
                        child: ListView.builder(
                          controller: _tickerScrollController,
                          scrollDirection: Axis.horizontal,
                          physics: const NeverScrollableScrollPhysics(),
                          itemCount: 1,
                          itemBuilder: (context, index) {
                            return Container(
                              alignment: Alignment.center,
                              padding: const EdgeInsets.only(left: 16),
                              child: Row(
                                children: [
                                  ..._tickerAlerts.map((alert) {
                                    return InkWell(
                                      onTap: () => _convertAlertToTask(alert["task"]!, alert["display"]!),
                                      splashColor: Colors.orange.withOpacity(0.3),
                                      highlightColor: Colors.transparent,
                                      child: Padding(
                                        padding: const EdgeInsets.only(right: 48.0),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          children: [
                                            Text(
                                              "${alert["display"]} ",
                                              style: const TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.w500),
                                            ),
                                            Container(
                                              padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                                              decoration: BoxDecoration(
                                                color: Colors.orange.shade800.withOpacity(0.4),
                                                borderRadius: BorderRadius.circular(4),
                                                border: Border.all(color: Colors.orange.shade600, width: 0.5),
                                              ),
                                              child: const Text(
                                                "⚡ Convert to Task",
                                                style: TextStyle(color: Colors.orangeAccent, fontSize: 9, fontWeight: FontWeight.bold),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    );
                                  }).toList(),
                                  const SizedBox(width: 120),
                                ],
                              ),
                            );
                          },
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 32),

                // ================= MODULE 2: CONTEXTUAL QUICK ACTION HUB =================
                _buildSectionHeader("OPERATIONAL TACTICAL HUB"),
                const SizedBox(height: 12),
                GridView.count(
                  crossAxisCount: 2,
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  mainAxisSpacing: 12,
                  crossAxisSpacing: 12,
                  childAspectRatio: 1.4,
                  children: [
                    _buildQuickActionCard(
                      icon: Icons.qr_code_scanner_rounded,
                      title: "Scan Ear Tag",
                      subtitle: "Instant profile search",
                      onTap: () => _showMockScanner(context),
                    ),
                    _buildQuickActionCard(
                      icon: Icons.medication_liquid_outlined,
                      title: "Log Treatment",
                      subtitle: "Rapid health report",
                      onTap: () {},
                    ),
                    _buildQuickActionCard(
                      icon: Icons.scale_outlined,
                      title: "Record Weight",
                      subtitle: "Update growth logs",
                      onTap: () {},
                    ),
                    _buildQuickActionCard(
                      icon: Icons.pie_chart_outline_rounded,
                      title: "Cash Allocation",
                      subtitle: "Review cost metrics",
                      onTap: () {},
                    ),
                  ],
                ),
                const SizedBox(height: 32),

                // ================= MODULE 3: VISUAL LIFE-CYCLE BREEDING GESTATION TRACKER =================
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    _buildSectionHeader("ACTIVE GESTATION TRACKING"),
                    Text(
                      "3 Pregnant",
                      style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: primaryGreen),
                    )
                  ],
                ),
                const SizedBox(height: 12),
                _buildGestationTrackerCard(
                  goatId: "GT-042 (Daisy)",
                  breed: "Pure Boer",
                  daysRemaining: 34,
                  progressValue: 0.77,
                ),
                const SizedBox(height: 12),
                _buildGestationTrackerCard(
                  goatId: "GT-089 (Flora)",
                  breed: "Kalahari Red",
                  daysRemaining: 112,
                  progressValue: 0.25,
                ),
                const SizedBox(height: 32),

                // ================= MODULE 4: INTERACTIVE DAILY SHIFT CHECKLIST =================
                _buildSectionHeader("DAILY OPERATIONS CHECKLIST"),
                const SizedBox(height: 12),
                
                // 👈 Embedded subtle layout loader mechanism for task items list updates
                _isLoadingDashboard 
                ? Padding(
                    padding: const EdgeInsets.symmetric(vertical: 20.0),
                    child: Center(child: CircularProgressIndicator(valueColor: AlwaysStoppedAnimation<Color>(primaryGreen))),
                  )
                : Container(
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: const Color(0xFFE2E8F0)),
                    ),
                    child: ListView.separated(
                      shrinkWrap: true,
                      physics: const NeverScrollableScrollPhysics(),
                      itemCount: _dailyTasks.length,
                      separatorBuilder: (context, index) => const Divider(height: 1, color: Color(0xFFE2E8F0)),
                      itemBuilder: (context, index) {
                        final task = _dailyTasks[index];
                        return ListTile(
                          contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                          leading: InkWell(
                            borderRadius: BorderRadius.circular(20),
                            onTap: () => _toggleTaskDatabaseState(index, task), // 👈 Hooked up to live Django Toggle handler
                            child: Padding(
                              padding: const EdgeInsets.all(4.0),
                              child: Icon(
                                task["done"] ? Icons.check_circle_rounded : Icons.radio_button_unchecked_rounded,
                                color: task["done"] ? primaryGreen : const Color(0xFF94A3B8),
                                size: 22,
                              ),
                            ),
                          ),
                          title: Text(
                            task["task"],
                            style: TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.w500,
                              color: task["done"] ? const Color(0xFF94A3B8) : const Color(0xFF0F172A),
                              decoration: task["done"] ? TextDecoration.lineThrough : TextDecoration.none,
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                const SizedBox(height: 24),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildSectionHeader(String text) {
    return Text(
      text,
      style: const TextStyle(
        fontSize: 11,
        fontWeight: FontWeight.bold,
        color: Color(0xFF64748B),
        letterSpacing: 0.8,
      ),
    );
  }

  Widget _buildQuickActionCard({
    required IconData icon,
    required String title,
    required String subtitle,
    required VoidCallback onTap,
  }) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: const Color(0xFFE2E8F0)),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(icon, color: Colors.orange.shade700, size: 24),
            const SizedBox(height: 10),
            Text(
              title,
              style: const TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: Color(0xFF0F172A)),
            ),
            const SizedBox(height: 2),
            Text(
              subtitle,
              style: TextStyle(fontSize: 11, color: Colors.grey.shade500),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildGestationTrackerCard({
    required String goatId,
    required String breed,
    required int daysRemaining,
    required double progressValue,
  }) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                goatId,
                style: const TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: Color(0xFF0F172A)),
              ),
              Text(
                "$daysRemaining days left",
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: Colors.orange.shade700),
              ),
            ],
          ),
          const SizedBox(height: 4),
          Text(
            "Breed group: $breed",
            style: TextStyle(fontSize: 12, color: Colors.grey.shade500),
          ),
          const SizedBox(height: 14),
          ClipRRect(
            borderRadius: BorderRadius.circular(8),
            child: LinearProgressIndicator(
              value: progressValue,
              minHeight: 8,
              backgroundColor: const Color(0xFFF1F5F9),
              valueColor: AlwaysStoppedAnimation<Color>(Colors.green.shade700),
            ),
          ),
        ],
      ),
    );
  }

  void _showMockScanner(BuildContext context) {
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))),
      builder: (context) {
        return Container(
          padding: const EdgeInsets.all(24),
          height: 320,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text(
                "RFID / EAR TAG SCANNER",
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, letterSpacing: 1),
              ),
              const SizedBox(height: 24),
              Container(
                width: 140,
                height: 100,
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.orange.shade700, width: 2),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Stack(
                  alignment: Alignment.center,
                  children: [
                    Icon(Icons.camera_alt_outlined, color: Colors.grey, size: 32),
                    Divider(color: Colors.red, thickness: 2, indent: 8, endIndent: 8),
                  ],
                ),
              ),
              const SizedBox(height: 20),
              Text(
                "Hold ear tag within scanning parameters...",
                style: TextStyle(fontSize: 13, color: Colors.grey.shade500),
              ),
              const SizedBox(height: 16),
              TextButton(
                onPressed: () {
                  Navigator.pop(context);
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text("Simulated Tag detected: ID A101 (Lucky)")),
                  );
                },
                child: Text("Simulate Tag Detect (A101)", style: TextStyle(color: Colors.green.shade700, fontWeight: FontWeight.bold)),
              )
            ],
          ),
        );
      },
    );
  }
}